// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6f9Iww62naIXbKIolk2c2MqTPmAinhNk',
    appId: '1:861050608779:web:8cdbc99c6d848734d5888e',
    messagingSenderId: '861050608779',
    projectId: 'learning-487da',
    authDomain: 'learning-487da.firebaseapp.com',
    storageBucket: 'learning-487da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2vt91ugLS1fNGaR0h7Fpz9bpEZ3khcQ8',
    appId: '1:861050608779:android:112e8afe276fc8abd5888e',
    messagingSenderId: '861050608779',
    projectId: 'learning-487da',
    storageBucket: 'learning-487da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEbpU2Xpkw0x7-0HKfc3S4SIW3e5ozfHU',
    appId: '1:861050608779:ios:9342b37f946aebcad5888e',
    messagingSenderId: '861050608779',
    projectId: 'learning-487da',
    storageBucket: 'learning-487da.appspot.com',
    androidClientId: '861050608779-1g8rg3eu0rmo8af5221t2kb3aqv128ce.apps.googleusercontent.com',
    iosClientId: '861050608779-vpuhes8kerd17dtgrsv0aguk48uj5apn.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEbpU2Xpkw0x7-0HKfc3S4SIW3e5ozfHU',
    appId: '1:861050608779:ios:123632976c895c43d5888e',
    messagingSenderId: '861050608779',
    projectId: 'learning-487da',
    storageBucket: 'learning-487da.appspot.com',
    androidClientId: '861050608779-1g8rg3eu0rmo8af5221t2kb3aqv128ce.apps.googleusercontent.com',
    iosClientId: '861050608779-4vsps0ief55vtjh84l06lirq3tq8r3og.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuth.RunnerTests',
  );
}
